file = {
    (expression ~ NEWLINE ~ expression ~ NEWLINE ~ NEWLINE*)+
}

expression = {        // To recognize an expression...
    number            //   first try to take a number...
    | list          //   or, if that fails, the string "true".
}

list = {
	"[" ~ expression* ~ ("," ~ expression)* ~ "]"
}

number = {            // To recognize a number...
    ASCII_DIGIT+      //   take as many ASCII digits as possible (at least one).
}